spring:
  application:
    name: api-gateway

  config:
    import: optional:file:.env[.properties]

jwt:
  secret-key: ${JWT_SECRET_KEY}
  
services:
  user: ${USER_SERVICE_URL:http://localhost:4002}
  carpool: ${CARPOOL_SERVICE_URL:http://localhost:4000}
  driver: ${DRIVER_SERVICE_URL:http://localhost:4004}
  geospatial: ${GEOSPATIAL_SERVICE_URL:http://localhost:4001}
  notification: ${NOTIFICATION_SERVICE_URL:http://localhost:4007}
  chat: ${CHAT_SERVICE_URL:http://localhost:4006}
  websocket: ${WEBSOCKET_SERVICE_URL:http://localhost:4100}

server:
  port: ${SERVER_PORT:4500}
