spring:
  application:
    name: driver-verification-service

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:password}
 
aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  bucket-name: ${AWS_BUCKET_NAME:tompang-carpool}
  endpoint: ${AWS_ENDPOINT:https://s3.amazonaws.com} # default aws
  local: ${AWS_IS_LOCAL:false}

server:
  port: ${SERVER_PORT:4005}