spring:
  application:
    name: carpool-service
  
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5440}/${POSTGRES_DB:carpool-service}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
        specific.avro.reader: true

    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer 
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:password}

kurrentdb:
  host: ${KURRENTDB_HOST:localhost}
  port: ${KURRENTDB_PORT:2113}
  tls: false

aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  bucket-name: ${AWS_BUCKET_NAME:tompang-carpool}
  endpoint: ${AWS_ENDPOINT:https://s3.amazonaws.com} # default aws
  local: ${AWS_IS_LOCAL:false}

server:
  port: ${SERVER_PORT:4000}

logging:
  level:
    org:
      apache:
        kafka: ERROR
    io:
      confluent: ERROR