spring:
  data:
    redis:
      host: redis
      port: ${REDIS_PORT:6379}

  application:
    name: geospatial-service

  config:
    import: optional:file:.env[.properties]

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:password}

aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  bucket-name: ${AWS_BUCKET_NAME:tompang-carpool}
  endpoint: ${AWS_ENDPOINT:https://s3.amazonaws.com} # default aws
  local: ${AWS_IS_LOCAL:false}

onemap:
  email: ${ONEMAP_API_EMAIL:tompangcarpool@gmail.com} # provided a burner onemap api account for convenience
  password: ${ONEMAP_API_PASSWORD:tompangcarpoolonemapAPI!}

server:
  port: ${SERVER_PORT:4001}

debug: true